### ISSUE TITLE
Mac Version

### ISSUE THREAD

**Issue by danielnovello** [ThomasHolbrook/AUSSTSetup#1]
I have created a simple script for Mac OS X Server.
Just copy paste this into your Terminal:
 
bash <(curl -Ls https://raw.githubusercontent.com/djquazzi/Scripts/master/ausstsetup.sh)

Let me know if it helps...

**Comment by ThomasHolbrook** [comment]
Cool, ill add it to the page :) 

Thanks for sharing

Tom
